title: 'Bruno Daniel Gonçalves'
default_lang: en
author:
  name: 'Bruno Daniel Gonçalves'
  email: brunodgoncalves32@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Engineer / Programmer / Musician'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
